### ISSUE TITLE
Ordinals broken

### ISSUE THREAD

**Issue by namazso** [Tylous/FaceDancer#2]
Hi,

I just ran into this project as I recently made [a similar one](https://github.com/namazso/dll-proxy-generator), with the difference that it makes binaries. I checked the source code of this and noticed a bug:

https://github.com/Tylous/FaceDancer/blob/main/exports/src/exports.rs#L13

You expect Goblin's export listing to be actually correct, but that is a mistake — if you read Goblin's source, they actually parse from the names table, so ordinal only exports will be completely missing.

**Comment by Tylous** [comment]
Hey, appreciate you bringing this up, but I have to push back on this claim.

Ordinals only are not as common these days, and just because they're being used doesn't automatically mean there's a bug. What you're seeing is intended behavior, not an issue with the code. Assuming there's a bug without fully understanding how things are designed to work can lead to confusion. In this case, the intention of this recon module is to generate the required definition file for dlls not already in FaceDancer. It is a starting point not the total sum of a situation as such it is up to the user to them make any modifications to said file to get it to work with ordinal only exports.

In future things like this, are considered an "Enhancement" or "Feature Request" rather then a bug. I will be closing this as it is not a bug. 

Have a great day.

**Comment by namazso** [comment]
So, just that I get it right: Generating a proxy dll with FaceDancer for a dll that is imported by ordinal by the attacked application, rendering the application inoperable is the expected behavior?

**Comment by Tylous** [comment]
Nope you don't have it correct at all. The ordinals are still there and there, there for they can can be imported by them if needed and using these generated .def files doesn't break any thing. Here is an example of a system DLL. I choose it because its already part of FaceDancer and it's known to be working. If we look at it in CFF explorer we can see the ordinals and their order: 
<img width="1077" alt="image" src="https://github.com/user-attachments/assets/6b76f564-ce2f-4e47-9a9f-9e69cad0627f">
Now taking the same file and using FaceDancer's recon mode to generate us a Def we can see that it the ordinal numbers are there and it compiles just fine. 
<img width="1558" alt="image" src="https://github.com/user-attachments/assets/ce8fb4c8-4438-4e6a-9a40-1103729b78b9">
Using CFF Explorer again we can see that this newly generated DLL has the proper ordinal numbers along with a new one we added for shellcode.
<img width="917" alt="image" src="https://github.com/user-attachments/assets/1ffdc373-7d14-4e62-b80d-0a881fcf5adc">


Now deploying it we can see it works just fine.
<img width="1130" alt="image" src="https://github.com/user-attachments/assets/987c5ca1-fa85-4588-b4c2-1704f820a874">

and as I said before this is just the the recon module part not the entire sum of the tool.
